### PR TITLE
Initial work for zero copy deserialization

### PR DESCRIPTION
**Pull request by demfabris**
Here we begin the refactor to support zero copy deser.

- Refactor public api `deserialize` to support borrowed fields. Essentially telling serde that the input buffer lives at least as long as `'de` lifetime. 

I'm struggling to find out why this test is currently panicking with `Message("invalid type: string \"asd\", expected a borrowed string")`. It panicks at line 407 inside the `deserialize_tuple` function.

We probably also need to refactor the custom deserializer to not use a `BufReader` since this defeats the purpose of zero copying. Thoughts? @tobiemh

### CODE REVIEW

**Comment by demfabris** [comment]
Possible workaround:
```rust
mod tests {
	use super::*;

	#[derive(serde::Deserialize)]
	struct Foo<'a> {
		#[serde(borrow)]
		a: std::borrow::Cow<'a, str>,
	}

	#[test]
	fn test() {
		let b = b"asd";
		let foo: Foo<'_> = deserialize(b).unwrap();
	}
}
```

Not sure how that behaves internally

**Comment by tobiemh** [comment]
Hi @demfabris , awesome. I'll need to give this a little (probably a lot 😖😀) of thought.

The `msgpack` deserializer/serializer https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/src/decode.rs#L909-L1003, allows for both deserialization to borrowed data, in addition to owned data at the same time. I'll probably need to look closely at how they are doing it there.

**Comment by tobiemh** [comment]
On a side note @demfabris, as this 'change' is over 3 different repositories, maybe we can look at the `surrealdb-derive` changes only, and get these merged so that they work with the current implementation, and future implementations. Perhaps using a different procedural macro name. Or is there a way of making the macro work for both owned and borrower (with lifetimes) data structures at the same time (this would be the ideal)...?

**Comment by demfabris** [comment]
Sure, we can make a new release in `surrealdb-derive`. Just don't use the new version in `surrealdb` yet

**Comment by tobiemh** [comment]
Hi @demfabris I'm going to close this as the repository has been updated considerably recently, with changes designed to get zero-copy deserialisation working!

If you spot anything, then definitely let us know 🎉🚀👍!

**Pull request closed without merging**
